import React from 'react'

const About = () => {
    return (
        <div className='h-screen flex items-center bg-secondary justify-center'>
            <p className='px-6 text-justify'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quo mollitia libero omnis suscipit rerum nobis quasi sapiente consectetur in eaque natus et alias ad eligendi, consequuntur ullam incidunt tempora dignissimos placeat nisi dolor iste quaerat. Necessitatibus enim sapiente placeat! Impedit autem incidunt minima enim magnam ipsam vero consequuntur officia repudiandae voluptas, debitis corporis est necessitatibus nobis, ab beatae assumenda illo nemo laboriosam modi delectus, iste commodi rerum labore? Expedita quasi commodi rem quis iusto et officia, in saepe fuga illo alias ipsa incidunt quae optio hic asperiores amet neque veritatis eos voluptatibus soluta rerum ea consequuntur. Inventore nisi culpa atque facilis totam cupiditate non fuga minus omnis ad? Reiciendis dolorum minus, consequuntur facilis, qui deleniti, dolor consectetur ab sed earum soluta? Nobis est quidem recusandae itaque? Officia provident in molestiae blanditiis distinctio unde, quam explicabo. Cupiditate expedita fuga omnis tempore alias quas, est soluta quaerat nisi aliquam culpa consequatur quis eos eaque illo ratione vero repellendus libero porro. Qui nostrum fugiat pariatur voluptas voluptatum molestiae recusandae ipsum. Autem illum ad magnam porro tempore aliquid, natus ipsum similique nam iure voluptatem voluptate repellendus harum. Commodi ea eum ullam velit aperiam nostrum eius laboriosam dolor? Numquam illo molestiae tempore sunt porro vitae ratione tempora, ut repudiandae inventore, ducimus dolor et! Harum dolores veritatis explicabo iure adipisci minus culpa facilis cupiditate consequatur, mollitia, quidem maiores rerum tenetur eius non odit omnis tempore corrupti laudantium aspernatur error. Quisquam in aliquid sapiente debitis! Maiores porro, optio deserunt temporibus corporis ad modi, velit aut labore rem quod non, asperiores a aperiam. Culpa vel et aliquid nobis asperiores ducimus dolorem eos, blanditiis pariatur velit veniam adipisci facilis obcaecati sunt dolor odio itaque, mollitia ipsa! Nostrum praesentium fuga alias suscipit minus veniam, tenetur excepturi! Reiciendis repellendus, error numquam non sequi, quasi eum excepturi accusamus sunt consectetur sapiente.
            </p>
        </div>
    )
}

export default About